class Player < ApplicationRecord
  belongs_to :team
  has_many :gameweek_stats
  has_many :gameweeks, through: :gameweek_stats

  validates :web_name, presence: true

  def fixtures
    team.fixtures
  end
end

# Example of a player response in the api
# {
#   "can_transact": true,
#   "can_select": true,
#   "chance_of_playing_next_round": 100,
#   "chance_of_playing_this_round": 100,
#   "code": 223094,
#   "cost_change_event": -1,
#   "cost_change_event_fall": 1,
#   "cost_change_start": -2,
#   "cost_change_start_fall": 2,
#   "dreamteam_count": 3,
#   "element_type": 4,
#   "ep_next": "4.1",
#   "ep_this": "4.1",
#   "event_points": 2,
#   "first_name": "Erling",
#   "form": "3.6",
#   "id": 351,
#   "in_dreamteam": true,
#   "news": "",
#   "news_added": "2024-09-13T15:00:06.985607Z",
#   "now_cost": 148,
#   "photo": "223094.jpg",
#   "points_per_game": "6.0",
#   "removed": false,
#   "second_name": "Haaland",
#   "selected_by_percent": "34.5",
#   "special": false,
#   "squad_number": null,
#   "status": "a",
#   "team": 13,
#   "team_code": 43,
#   "total_points": 102,
#   "transfers_in": 2864316,
#   "transfers_in_event": 15025,
#   "transfers_out": 4902372,
#   "transfers_out_event": 246194,
#   "value_form": "0.2",
#   "value_season": "6.9",
#   "web_name": "Haaland",
#   "region": 161,
#   "team_join_date": "2022-07-01",
#   "minutes": 1529,
#   "goals_scored": 13,
#   "assists": 1,
#   "clean_sheets": 3,
#   "goals_conceded": 25,
#   "own_goals": 0,
#   "penalties_saved": 0,
#   "penalties_missed": 0,
#   "yellow_cards": 2,
#   "red_cards": 0,
#   "saves": 0,
#   "bonus": 15,
#   "bps": 451,
#   "influence": "534.8",
#   "creativity": "156.8",
#   "threat": "919.0",
#   "ict_index": "161.3",
#   "starts": 17,
#   "expected_goals": "13.10",
#   "expected_assists": "0.91",
#   "expected_goal_involvements": "14.01",
#   "expected_goals_conceded": "25.31",
#   "influence_rank": 5,
#   "influence_rank_type": 1,
#   "creativity_rank": 127,
#   "creativity_rank_type": 13,
#   "threat_rank": 2,
#   "threat_rank_type": 1,
#   "ict_index_rank": 4,
#   "ict_index_rank_type": 1,
#   "corners_and_indirect_freekicks_order": null,
#   "corners_and_indirect_freekicks_text": "",
#   "direct_freekicks_order": 3,
#   "direct_freekicks_text": "",
#   "penalties_order": 1,
#   "penalties_text": "",
#   "expected_goals_per_90": 0.77,
#   "saves_per_90": 0,
#   "expected_assists_per_90": 0.05,
#   "expected_goal_involvements_per_90": 0.82,
#   "expected_goals_conceded_per_90": 1.49,
#   "goals_conceded_per_90": 1.47,
#   "now_cost_rank": 1,
#   "now_cost_rank_type": 1,
#   "form_rank": 83,
#   "form_rank_type": 14,
#   "points_per_game_rank": 7,
#   "points_per_game_rank_type": 2,
#   "selected_rank": 4,
#   "selected_rank_type": 2,
#   "starts_per_90": 1,
#   "clean_sheets_per_90": 0.18
# }